version: '3.8'

networks:
  npServer:
    driver: bridge
services:
  npServer:
    image: aoshiguchen/neutrino-proxy-server:latest
    container_name: compose-npServer
    hostname: npServer
    restart: always
    environment:
        TZ: Asia/Shanghai
        LANG: zh_CN.UTF-8
    volumes:
      - ./config:/root/neutrino-proxy/config
      - ./data:/root/neutrino-proxy/data
      - ./logs:/root/neutrino-proxy/logs
    ports:
      - "8888:8888"
      - "9000:9000"
      - "9002:9002"
      - "9101-9120:9101-9120"
    networks:
      - npServer